<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
    .header { text-align: center; margin-bottom: 20px; }
    .details { width: 100%; margin-bottom: 20px; }
    .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    .table th, .table td { border: 1px solid #ddd; padding: 8px; }
    .right { text-align: right; }
  </style>
</head>
<body>
  <div class="header">
    <h2>{{ config('app.name') }}</h2>
    <div>{{ config('app.url') }}</div>
  </div>

  <div>
    <strong>Invoice:</strong> {{ $invoice_number }} <br>
    <strong>Date:</strong> {{ now()->toDateString() }} <br>
    <strong>To:</strong> {{ $transaction->user->name ?? $transaction->user->email }} <br>
    <strong>Transaction ID:</strong> {{ $transaction->id }}
  </div>

  <table class="table">
    <thead>
      <tr><th>Description</th><th class="right">Amount ({{ $transaction->currency }})</th></tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ $transaction->package->name ?? 'Package' }}</td>
        <td class="right">{{ number_format($transaction->amount,2) }}</td>
      </tr>
      <tr>
        <td><strong>Total</strong></td>
        <td class="right"><strong>{{ number_format($transaction->amount,2) }}</strong></td>
      </tr>
    </tbody>
  </table>

  <div>
    <small>Invoice generated by {{ config('app.name') }}.</small>
  </div>
</body>
</html>
